LoadModule ssl_module /usr/lib/apache2/modules/mod_ssl.so
LoadModule dir_module /usr/lib/apache2/modules/mod_dir.so
LoadModule mime_module /usr/lib/apache2/modules/mod_mime.so
LoadModule http2_module /usr/lib/apache2/modules/mod_http2.so
LoadModule alias_module /usr/lib/apache2/modules/mod_alias.so
LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
LoadModule rewrite_module /usr/lib/apache2/modules/mod_rewrite.so
LoadModule headers_module /usr/lib/apache2/modules/mod_headers.so
LoadModule evasive_module /usr/lib/apache2/modules/mod_evasive.so
LoadModule unique_id_module /usr/lib/apache2/modules/mod_unique_id.so
LoadModule security2_module /usr/lib/apache2/modules/mod_security2.so
LoadModule mpm_event_module /usr/lib/apache2/modules/mod_mpm_event.so
LoadModule authz_core_module /usr/lib/apache2/modules/mod_authz_core.so
LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
LoadModule access_compat_module /usr/lib/apache2/modules/mod_access_compat.so
LoadModule socache_shmcb_module /usr/lib/apache2/modules/mod_socache_shmcb.so

ServerRoot "/etc/apache2"
ServerAdmin admin@gmail.com
ServerName vulnerable1.com

TypesConfig /etc/mime.types

<IfModule unixd_module>
    User www-data
    Group www-data
</IfModule>

ServerTokens Prod
ServerSignature Off
TraceEnable Off
SecServerSignature " "

SSLSessionCache shmcb:/var/run/apache2/ssl_scache(512000)
SSLSessionCacheTimeout 300

<Directory />
    AllowOverride none
    Require all denied
</Directory>

<Files ".ht*">
    Require all denied
</Files>

ErrorLog /dev/stderr
LogLevel warn

<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    <IfModule logio_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>

    CustomLog /dev/stdout common
</IfModule>

<IfModule evasive_module>
    DOSHashTableSize    3097
    DOSPageCount        2
    DOSSiteCount        50
    DOSPageInterval     1
    DOSSiteInterval     1
    DOSBlockingPeriod   10
    DOSEmailNotify      root@localhost
    
    # DOSWhitelist        127.0.0.1
</IfModule>

Include /etc/modsecurity/modsecurity.conf
Include /etc/apache2/sites-available/vulnerable1.com.conf
